version: '3.9'

services:
  backend:
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: backend-dev
    networks:
      - backend  
    env_file: .env
    restart: unless-stopped
    ports:
      - 4000:3001
    depends_on:
      - postgres

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: frontend-dev
    restart: unless-stopped  
    ports:
      - 8081:80
    networks:
      - frontend

  postgres:
    container_name: postgres
    image: postgres
    networks:
      - backend
    restart: always
    env_file: .env
    volumes:
     - postgres_data:/data/postgres
    
  

volumes:
  postgres_data:

networks:
  backend:
  frontend: